import { Hospital, LocationType, HospitalType } from "../types";

// Function to simulate changing bed availability
const getRandomBedsAvailable = (min: number, max: number): number => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

// Merged hospital data with real coordinates and Google Maps pin links using the query parameter format.
const hospitalData = [
  // ----------------- Bulandshahr Hospitals from Original File -----------------
  {
    id: "1",
    name: "Mohan Hospital And Heart Centre",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology",
    priceRange: "₹3,000 - ₹8,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Opposite Old Jail, Bulandshahr, Uttar Pradesh 203001",
    coordinates: { lat: 28.409068, lng: 77.849452 },
    minBeds: 5,
    maxBeds: 12,
    gmaplink: "https://www.google.com/maps?q=Opposite+Old+Jail,+Bulandshahr,+Uttar+Pradesh+203001"
  },
  {
    id: "2",
    name: "Rana Hospital",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹2,500 - ₹6,000 per day",
    contactNumber: "8191002002",
    ambulanceNumber: "108",
    address: "Delhi Road, Bhoor, Near R.T.O Office, Bulandshahr, Uttar Pradesh 203001",
    coordinates: { lat: 28.410500, lng: 77.848200 },
    minBeds: 3,
    maxBeds: 10,
    gmaplink: "https://www.google.com/maps?q=Delhi+Road,+Bhoor,+Near+R.T.O+Office,+Bulandshahr,+Uttar+Pradesh+203001"
  },
  {
    id: "3",
    name: "Shrimati Champa Devi Medical Centre",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Maternity",
    priceRange: "₹2,000 - ₹5,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "DM Colony Road, Awaas Vikas Colony, Bulandshahr, Uttar Pradesh",
    coordinates: { lat: 28.409600, lng: 77.849000 },
    minBeds: 2,
    maxBeds: 8,
    gmaplink: "https://www.google.com/maps?q=DM+Colony+Road,+Awaas+Vikas+Colony,+Bulandshahr,+Uttar+Pradesh"
  },
  {
    id: "4",
    name: "Garg Hospital",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹2,000 - ₹5,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Khurja Tempo Stand, K.P. Road, Bulandshahr, Uttar Pradesh",
    coordinates: { lat: 28.412000, lng: 77.850000 },
    minBeds: 4,
    maxBeds: 9,
    gmaplink: "https://www.google.com/maps?q=Khurja+Tempo+Stand,+K.P.+Road,+Bulandshahr,+Uttar+Pradesh"
  },
  {
    id: "5",
    name: "Kilkari Child Care Hospital",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Pediatrics",
    priceRange: "₹2,500 - ₹6,500 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "On Delhi Road, Beside Natraj Hotel, Near Kala Aam Chauraha, Bulandshahr, Uttar Pradesh 203001",
    coordinates: { lat: 28.411500, lng: 77.848800 },
    minBeds: 3,
    maxBeds: 7,
    gmaplink: "https://www.google.com/maps?q=On+Delhi+Road,+Beside+Natraj+Hotel,+Near+Kala+Aam+Chauraha,+Bulandshahr,+Uttar+Pradesh+203001"
  },
  {
    id: "6",
    name: "Kalyan Singh Government Medical College",
    location: "Bulandshehar" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹500 - ₹2,000 per day",
    contactNumber: "9411259674",
    ambulanceNumber: "108",
    address: "KSGMC Campus, Bulandshahr, Uttar Pradesh 203001",
    coordinates: { lat: 28.407000, lng: 77.847500 },
    minBeds: 10,
    maxBeds: 30,
    gmaplink: "https://www.google.com/maps?q=KSGMC+Campus,+Bulandshahr,+Uttar+Pradesh+203001"
  },
  // ----------------- Bulandshahr Hospitals from Word Document -----------------
  {
    id: "30",
    name: "Rama Hospital and Jaishipra Medical Centre",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Mansarovar Colony, K.P. Road, Bulandshahr, Uttar Pradesh",
    coordinates: { lat: 28.410200, lng: 77.848700 },
    gmaplink: "https://www.google.com/maps?q=Mansarovar+Colony,+K.P.+Road,+Bulandshahr,+Uttar+Pradesh"
  },
  {
    id: "31",
    name: "Ojas Eye Care",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Ophthalmology",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Ojas Eye Care Hospital, In front of Himalya Petrol Pump, Delhi Road, Bhoor, Bulandshahr, Uttar Pradesh 203001",
    coordinates: { lat: 28.409700, lng: 77.848500 },
    gmaplink: "https://www.google.com/maps?q=Ojas+Eye+Care+Hospital,+Delhi+Road,+Bhoor,+Bulandshahr,+Uttar+Pradesh+203001"
  },
  {
    id: "32",
    name: "Vimla Hospital and Maternity Centre",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Maternity",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Bulandshahr Tehsil, Bulandshahr, Uttar Pradesh",
    coordinates: { lat: 28.409300, lng: 77.849100 },
    gmaplink: "https://www.google.com/maps?q=Bulandshahr+Tehsil,+Bulandshahr,+Uttar+Pradesh"
  },
  {
    id: "33",
    name: "Bakson Homoeopathic Medical College & Hospital",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Homeopathy",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Malakpur, Bulandshahr, Uttar Pradesh",
    coordinates: { lat: 28.409400, lng: 77.849000 },
    gmaplink: "https://www.google.com/maps?q=Malakpur,+Bulandshahr,+Uttar+Pradesh"
  },
  {
    id: "34",
    name: "Kailash Hospital",
    location: "Bulandshehar" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Plot No 203, Wazidpur, G.T. Road, N.H. 91, Khurja, Bulandshahr, Uttar Pradesh 203131",
    coordinates: { lat: 28.409068, lng: 77.849452 },
    gmaplink: "https://www.google.com/maps?q=Plot+No+203,+Wazidpur,+G.T.+Road,+N.H.+91,+Khurja,+Bulandshahr,+Uttar+Pradesh+203131"
  },
  // ----------------- Gurgaon Hospitals from Original File -----------------
  {
    id: "7",
    name: "Fortis Memorial Research Institute",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Oncology, Neurosciences, Renal Sciences, Organ Transplants, Orthopedics",
    priceRange: "₹15,000 - ₹35,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Sector - 44, Opposite HUDA City Centre, Gurgaon, Haryana 122002",
    coordinates: { lat: 28.434000, lng: 77.021000 },
    minBeds: 15,
    maxBeds: 40,
    gmaplink: "https://www.google.com/maps?q=Sector+-+44,+Opposite+HUDA+City+Centre,+Gurgaon,+Haryana+122002"
  },
  {
    id: "8",
    name: "Medanta - The Medicity Hospital",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Neurology, Oncology, Orthopedics, Gastroenterology, Transplants",
    priceRange: "₹18,000 - ₹40,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Sector - 38, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.439000, lng: 77.038500 },
    minBeds: 20,
    maxBeds: 45,
    gmaplink: "https://www.google.com/maps?q=Sector+-+38,+Gurgaon,+Haryana+122001"
  },
  {
    id: "9",
    name: "Artemis Hospital",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Oncology, Neurosciences, Orthopedics, Gastroenterology, Nephrology",
    priceRange: "₹15,000 - ₹30,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Sector 51, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.458000, lng: 77.024000 },
    minBeds: 10,
    maxBeds: 35,
    gmaplink: "https://www.google.com/maps?q=Sector+51,+Gurgaon,+Haryana+122001"
  },
  {
    id: "10",
    name: "Max Super Speciality Hospital",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Oncology, Neurosciences, Orthopedics, Urology",
    priceRange: "₹14,000 - ₹32,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "B Block, Sushant Lok 1, Near Huda City Centre, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.450000, lng: 77.080000 },
    minBeds: 8,
    maxBeds: 30,
    gmaplink: "https://www.google.com/maps?q=B+Block,+Sushant+Lok+1,+Near+Huda+City+Centre,+Gurgaon,+Haryana+122001"
  },
  {
    id: "11",
    name: "Paras Hospitals",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Oncology, Neurosciences, Orthopedics, Gastroenterology, Nephrology",
    priceRange: "₹12,000 - ₹28,000 per day",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "C-1, Sushant Lok 1, Sector 43, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.442500, lng: 77.015000 },
    minBeds: 7,
    maxBeds: 25,
    gmaplink: "https://www.google.com/maps?q=C-1,+Sushant+Lok+1,+Sector+43,+Gurgaon,+Haryana+122001"
  },
  // ----------------- Gurgaon - Government (Original File) -----------------
  {
    id: "12",
    name: "General/Civil Hospital Gurgaon",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹500 - ₹3,000 per day",
    contactNumber: "0124-2320102",
    ambulanceNumber: "108",
    address: "Near Bus Stand, Opposite MCG, Gurugram, Haryana 122001",
    coordinates: { lat: 28.466000, lng: 77.032000 },
    minBeds: 15,
    maxBeds: 35,
    gmaplink: "https://www.google.com/maps?q=Near+Bus+Stand,+Opposite+MCG,+Gurugram,+Haryana+122001"
  },
  {
    id: "13",
    name: "SDH Sohna",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹500 - ₹2,500 per day",
    contactNumber: "0124-3266857",
    ambulanceNumber: "108",
    address: "Friends Colony, Sohna, Gurgaon",
    coordinates: { lat: 28.245000, lng: 77.065000 },
    minBeds: 10,
    maxBeds: 25,
    gmaplink: "https://www.google.com/maps?q=Friends+Colony,+Sohna,+Gurgaon"
  },
  // ----------------- Gurgaon Hospitals from Word Document -----------------
  {
    id: "35",
    name: "Manipal Hospital",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Neurology, Oncology, Orthopedics, Gastroenterology",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Ansal Plaza, Block F, Gol Chakkar, Near Palam Vihar, Gurgaon, Haryana 122017",
    coordinates: { lat: 28.455000, lng: 77.033000 },
    gmaplink: "https://www.google.com/maps?q=Ansal+Plaza,+Block+F,+Gol+Chakkar,+Near+Palam+Vihar,+Gurgaon,+Haryana+122017"
  },
  {
    id: "36",
    name: "CK Birla Hospital",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Obstetrics, Gynecology, Pediatrics, Orthopedics, Neonatology",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Sector 51, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.460000, lng: 77.032000 },
    gmaplink: "https://www.google.com/maps?q=Sector+51,+Gurgaon,+Haryana+122001"
  },
  {
    id: "37",
    name: "Park Hospital",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Neurology, Oncology, Orthopedics, General Surgery",
    priceRange: "Not Available",
    contactNumber: "1800 102 6767",
    ambulanceNumber: "108",
    address: "Q Block South City 2, Sohna Rd, Main, Sector 47, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.465000, lng: 77.035000 },
    gmaplink: "https://www.google.com/maps?q=Q+Block+South+City+2,+Sohna+Rd,+Sector+47,+Gurgaon,+Haryana+122001"
  },
  {
    id: "38",
    name: "Columbia Asia Hospital (now Manipal Hospital)",
    location: "Gurgaon" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Neurology, Oncology, Orthopedics, General Surgery",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Palam Vihar, Gurgaon, Haryana 122017",
    coordinates: { lat: 28.455500, lng: 77.033500 },
    gmaplink: "https://www.google.com/maps?q=Palam+Vihar,+Gurgaon,+Haryana+122017"
  },
  {
    id: "39",
    name: "SDH Haily Mandi",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "0124-2670516",
    ambulanceNumber: "108",
    address: "Haily Mandi, Gurgaon",
    coordinates: { lat: 28.445000, lng: 77.035000 },
    gmaplink: "https://www.google.com/maps?q=Haily+Mandi,+Gurgaon"
  },
  {
    id: "40",
    name: "Sheetla Hospital",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "0124-4066695-97, 0124-4079646",
    ambulanceNumber: "108",
    address: "New Railway Station, Gurgaon",
    coordinates: { lat: 28.446000, lng: 77.036000 },
    gmaplink: "https://www.google.com/maps?q=New+Railway+Station,+Gurgaon"
  },
  {
    id: "41",
    name: "Pushpanjali Hospital",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "9811122554",
    ambulanceNumber: "108",
    address: "John Hall Road, Civil Lines, Gurugram",
    coordinates: { lat: 28.447000, lng: 77.037000 },
    gmaplink: "https://www.google.com/maps?q=John+Hall+Road,+Civil+Lines,+Gurugram"
  },
  {
    id: "42",
    name: "Kalyani Hospital",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "0124-2303101-03",
    ambulanceNumber: "108",
    address: "Anamika Enclave, Mehrauli-Gurgaon Road, Opposite Government Girls College, Sector 14, Gurgaon, Haryana 122001",
    coordinates: { lat: 28.448000, lng: 77.038000 },
    gmaplink: "https://www.google.com/maps?q=Anamika+Enclave,+Mehrauli-Gurgaon+Road,+Gurgaon,+Haryana+122001"
  },
  {
    id: "43",
    name: "Alchemist Hospital",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "Not Available",
    ambulanceNumber: "108",
    address: "Sector 53, Gurugram",
    coordinates: { lat: 28.450000, lng: 77.040000 },
    gmaplink: "https://www.google.com/maps?q=Sector+53,+Gurugram"
  },
  {
    id: "44",
    name: "Sethi Hospital",
    location: "Gurgaon" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "0124-2321153",
    ambulanceNumber: "108",
    address: "Basai Road, Gurugram",
    coordinates: { lat: 28.451000, lng: 77.041000 },
    gmaplink: "https://www.google.com/maps?q=Basai+Road,+Gurugram"
  },
  // ----------------- Delhi Hospitals -----------------
  {
    id: "14",
    name: "All India Institute of Medical Sciences (AIIMS)",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty, including Cardiology, Neurology, Oncology, Trauma Care",
    priceRange: "₹1,000 - ₹5,000 per day",
    contactNumber: "+91-11-26588500 / 26588700",
    ambulanceNumber: "108",
    address: "Ansari Nagar, New Delhi - 110029",
    coordinates: { lat: 28.612700, lng: 77.229000 },
    minBeds: 30,
    maxBeds: 75,
    gmaplink: "https://www.google.com/maps?q=Ansari+Nagar,+New+Delhi+-+110029"
  },
  {
    id: "15",
    name: "Safdarjung Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty, Trauma Care, Cardiology, Orthopedics, Urology",
    priceRange: "₹800 - ₹4,000 per day",
    contactNumber: "+91-11-26730000",
    ambulanceNumber: "108",
    address: "Ring Road, New Delhi - 110029",
    coordinates: { lat: 28.607000, lng: 77.213000 },
    minBeds: 25,
    maxBeds: 60,
    gmaplink: "https://www.google.com/maps?q=Ring+Road,+New+Delhi+-+110029"
  },
  {
    id: "46",
    name: "Ram Manohar Lohia Hospital (RML)",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-23365525, +91-11-23404286",
    ambulanceNumber: "108",
    address: "Baba Kharak Singh Marg, Connaught Place, New Delhi - 110001",
    coordinates: { lat: 28.610000, lng: 77.220000 },
    gmaplink: "https://www.google.com/maps?q=Baba+Kharak+Singh+Marg,+Connaught+Place,+New+Delhi+-+110001"
  },
  {
    id: "47",
    name: "Lok Nayak Jai Prakash Narain (LNJP) Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty, Pediatrics, Obstetrics and Gynecology, Orthopedics",
    priceRange: "Not Available",
    contactNumber: "+91-11-23236000",
    ambulanceNumber: "108",
    address: "Jawaharlal Nehru Marg, New Delhi - 110002",
    coordinates: { lat: 28.611000, lng: 77.221000 },
    gmaplink: "https://www.google.com/maps?q=Jawaharlal+Nehru+Marg,+New+Delhi+-+110002"
  },
  {
    id: "48",
    name: "Guru Teg Bahadur (GTB) Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-22586262, +91-11-22588383",
    ambulanceNumber: "108",
    address: "Dilshad Garden, New Delhi - 110095",
    coordinates: { lat: 28.612000, lng: 77.222000 },
    gmaplink: "https://www.google.com/maps?q=Dilshad+Garden,+New+Delhi+-+110095"
  },
  {
    id: "49",
    name: "Deen Dayal Upadhyay Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-25494402, +91-11-25494403",
    ambulanceNumber: "108",
    address: "Hari Nagar, New Delhi - 110064",
    coordinates: { lat: 28.613000, lng: 77.223000 },
    gmaplink: "https://www.google.com/maps?q=Hari+Nagar,+New+Delhi+-+110064"
  },
  {
    id: "50",
    name: "Dr. Baba Saheb Ambedkar Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-27051011, +91-11-27051012",
    ambulanceNumber: "108",
    address: "Sector-6, Rohini, New Delhi - 110085",
    coordinates: { lat: 28.614000, lng: 77.224000 },
    gmaplink: "https://www.google.com/maps?q=Sector-6,+Rohini,+New+Delhi+-+110085"
  },
  {
    id: "51",
    name: "G.B. Pant Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Cardiology, Neurology, Gastroenterology",
    priceRange: "Not Available",
    contactNumber: "+91-11-23234242",
    ambulanceNumber: "108",
    address: "1, Jawaharlal Nehru Marg, New Delhi - 110002",
    coordinates: { lat: 28.615000, lng: 77.225000 },
    gmaplink: "https://www.google.com/maps?q=Jawaharlal+Nehru+Marg,+New+Delhi+-+110002"
  },
  {
    id: "52",
    name: "Chacha Nehru Bal Chikitsalaya",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Pediatrics",
    priceRange: "Not Available",
    contactNumber: "+91-11-22013373, +91-11-22013374",
    ambulanceNumber: "108",
    address: "Geeta Colony, New Delhi - 110031",
    coordinates: { lat: 28.616000, lng: 77.226000 },
    gmaplink: "https://www.google.com/maps?q=Geeta+Colony,+New+Delhi+-+110031"
  },
  {
    id: "53",
    name: "Lal Bahadur Shastri Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-22774145",
    ambulanceNumber: "108",
    address: "Khichripur, New Delhi - 110091",
    coordinates: { lat: 28.617000, lng: 77.227000 },
    gmaplink: "https://www.google.com/maps?q=Khichripur,+New+Delhi+-+110091"
  },
  {
    id: "54",
    name: "Acharya Shree Bhikshu Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-25423011",
    ambulanceNumber: "108",
    address: "Moti Nagar, New Delhi - 110015",
    coordinates: { lat: 28.618000, lng: 77.228000 },
    gmaplink: "https://www.google.com/maps?q=Moti+Nagar,+New+Delhi+-+110015"
  },
  {
    id: "55",
    name: "Jag Pravesh Chandra Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-22184453",
    ambulanceNumber: "108",
    address: "Shastri Park, New Delhi - 110031",
    coordinates: { lat: 28.619000, lng: 77.229000 },
    gmaplink: "https://www.google.com/maps?q=Shastri+Park,+New+Delhi+-+110031"
  },
  {
    id: "56",
    name: "Sardar Vallabh Bhai Patel Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-25885944",
    ambulanceNumber: "108",
    address: "Patel Nagar, New Delhi - 110008",
    coordinates: { lat: 28.620000, lng: 77.230000 },
    gmaplink: "https://www.google.com/maps?q=Patel+Nagar,+New+Delhi+-+110008"
  },
  {
    id: "57",
    name: "Babu Jagjivan Ram Memorial Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multispecialty",
    priceRange: "Not Available",
    contactNumber: "+91-11-27636955",
    ambulanceNumber: "108",
    address: "Jahangirpuri, New Delhi - 110033",
    coordinates: { lat: 28.621000, lng: 77.231000 },
    gmaplink: "https://www.google.com/maps?q=Jahangirpuri,+New+Delhi+-+110033"
  },
  {
    id: "58",
    name: "Dr. N.C. Joshi Memorial Hospital",
    location: "Delhi" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Orthopedics",
    priceRange: "Not Available",
    contactNumber: "+91-11-23622498",
    ambulanceNumber: "108",
    address: "Karol Bagh, New Delhi - 110005",
    coordinates: { lat: 28.622000, lng: 77.232000 },
    gmaplink: "https://www.google.com/maps?q=Karol+Bagh,+New+Delhi+-+110005"
  },
  // ----------------- Delhi Hospitals from Word Document (Private) -----------------
  {
    id: "59",
    name: "Fortis Escorts Heart Institute",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology & Cardio-surgery",
    priceRange: "Not Available",
    contactNumber: "011 2682 5000",
    ambulanceNumber: "108",
    address: "Okhla Road, New Delhi, Delhi 110025",
    coordinates: { lat: 28.610500, lng: 77.223000 },
    gmaplink: "https://www.google.com/maps?q=Okhla+Road,+New+Delhi,+110025"
  },
  {
    id: "60",
    name: "BLK-Max Super Speciality Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 3040 3040",
    ambulanceNumber: "108",
    address: "Pusa Rd, Radha Soami Satsang, Rajendra Place, New Delhi, Delhi 110005",
    coordinates: { lat: 28.611500, lng: 77.224500 },
    gmaplink: "https://www.google.com/maps?q=Pusa+Rd,+New+Delhi,+110005"
  },
  {
    id: "61",
    name: "Sir Ganga Ram Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 4225 4000",
    ambulanceNumber: "108",
    address: "Old Rajinder Nagar, Rajinder Nagar, New Delhi, Delhi 110060",
    coordinates: { lat: 28.612500, lng: 77.225500 },
    gmaplink: "https://www.google.com/maps?q=Old+Rajinder+Nagar,+New+Delhi,+110060"
  },
  {
    id: "62",
    name: "Manipal Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 4967 4967",
    ambulanceNumber: "108",
    address: "Sector 6 Dwarka, Dwarka, New Delhi, Delhi 110075",
    coordinates: { lat: 28.613500, lng: 77.226500 },
    gmaplink: "https://www.google.com/maps?q=Sector+6+Dwarka,+New+Delhi,+110075"
  },
  {
    id: "63",
    name: "Primus Super Speciality Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 6620 6630",
    ambulanceNumber: "108",
    address: "2, Chandragupta Marg, Opp Russian Embassy, Chanakyapuri, New Delhi, Delhi 110021",
    coordinates: { lat: 28.614500, lng: 77.227500 },
    gmaplink: "https://www.google.com/maps?q=2,+Chandragupta+Marg,+New+Delhi,+110021"
  },
  {
    id: "64",
    name: "Rajiv Gandhi Cancer Institute & Research Centre",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Oncology",
    priceRange: "Not Available",
    contactNumber: "011 4702 2222",
    ambulanceNumber: "108",
    address: "Sir Chotu Ram Marg, Sector - 5, Rohini Industrial Area, Rohini, New Delhi - 110085",
    coordinates: { lat: 28.615500, lng: 77.228500 },
    gmaplink: "https://www.google.com/maps?q=Sir+Chotu+Ram+Marg,+Rohini+Industrial+Area,+New+Delhi,+110085"
  },
  {
    id: "65",
    name: "Venkateshwar Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 4855 5555",
    ambulanceNumber: "108",
    address: "Sector 12 Rd, Sector 18, Sector 18A Dwarka, Dwarka, New Delhi, Delhi 110075",
    coordinates: { lat: 28.616500, lng: 77.229500 },
    gmaplink: "https://www.google.com/maps?q=Sector+12+Rd,+Dwarka,+New+Delhi,+110075"
  },
  {
    id: "66",
    name: "PSRI Multispeciality Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 3061 3000",
    ambulanceNumber: "108",
    address: "Press Enclave Marg, J Pocket, Phase II, Sheikh Sarai, New Delhi, Delhi 110017",
    coordinates: { lat: 28.617500, lng: 77.230500 },
    gmaplink: "https://www.google.com/maps?q=Press+Enclave+Marg,+New+Delhi,+110017"
  },
  {
    id: "67",
    name: "Aakash Healthcare Super Speciality Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 7121 2121",
    ambulanceNumber: "108",
    address: "Hospital Plot, Road No. 201, Sector 3, Dwarka, New Delhi, Delhi 110075",
    coordinates: { lat: 28.618500, lng: 77.231500 },
    gmaplink: "https://www.google.com/maps?q=Hospital+Plot,+Road+No.+201,+Dwarka,+New+Delhi,+110075"
  },
  {
    id: "68",
    name: "Dharamshila Narayana Superspeciality Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Oncology",
    priceRange: "Not Available",
    contactNumber: "011 4306 6666",
    ambulanceNumber: "108",
    address: "Dharamshila Marg, Vasundhara Enclave, New Delhi, Delhi 110096",
    coordinates: { lat: 28.619500, lng: 77.232500 },
    gmaplink: "https://www.google.com/maps?q=Dharamshila+Marg,+Vasundhara+Enclave,+New+Delhi,+110096"
  },
  {
    id: "69",
    name: "St. Stephen's Hospital",
    location: "Delhi" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General and Super Specialties",
    priceRange: "Not Available",
    contactNumber: "011 2396 6021",
    ambulanceNumber: "108",
    address: "Tis Hazari, Delhi 110054",
    coordinates: { lat: 28.620500, lng: 77.233500 },
    gmaplink: "https://www.google.com/maps?q=Tis+Hazari,+Delhi+110054"
  },
  // ----------------- Noida Hospitals (Original File) -----------------
  {
    id: "18",
    name: "Government Institute of Medical Sciences (GIMS)",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine, Surgery, Gynecology",
    priceRange: "₹800 - ₹3,500 per day",
    contactNumber: "+91 120 2345650",
    ambulanceNumber: "108",
    address: "Greater Noida, Uttar Pradesh",
    coordinates: { lat: 28.472000, lng: 77.510000 },
    minBeds: 15,
    maxBeds: 40,
    gmaplink: "https://www.google.com/maps?q=Greater+Noida,+Uttar+Pradesh"
  },
  {
    id: "19",
    name: "District Combined Hospital",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine, Pediatrics, Emergency Care",
    priceRange: "₹500 - ₹2,500 per day",
    contactNumber: "+91 120 2335245",
    ambulanceNumber: "108",
    address: "Sector 39, Noida, Uttar Pradesh",
    coordinates: { lat: 28.565000, lng: 77.345000 },
    minBeds: 12,
    maxBeds: 30,
    gmaplink: "https://www.google.com/maps?q=Sector+39,+Noida,+Uttar+Pradesh"
  },
  {
    id: "20",
    name: "Jaypee Hospital",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty services including Cardiology, Oncology, Neurology, and Orthopedics",
    priceRange: "₹14,000 - ₹35,000 per day",
    contactNumber: "0120-4122222",
    ambulanceNumber: "108",
    address: "Sector-128, Wish Town, Gautam Buddh Nagar, Noida",
    coordinates: { lat: 28.525000, lng: 77.405000 },
    minBeds: 15,
    maxBeds: 40,
    gmaplink: "https://www.google.com/maps?q=Sector-128,+Wish+Town,+Noida"
  },
  {
    id: "21",
    name: "Fortis Hospital",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Specializes in Cardiology, Oncology, Orthopedics, and Nephrology",
    priceRange: "₹13,000 - ₹32,000 per day",
    contactNumber: "0120-2400222",
    ambulanceNumber: "108",
    address: "B-22, Sector 62, Gautam Buddh Nagar, Noida",
    coordinates: { lat: 28.630000, lng: 77.360000 },
    minBeds: 12,
    maxBeds: 35,
    gmaplink: "https://www.google.com/maps?q=B-22,+Sector+62,+Noida"
  },
  // ----------------- Noida Hospitals from Word Document -----------------
  {
    id: "70",
    name: "Dr. Bhimrao Ambedkar Multi-Specialty Hospital",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multi-Specialty Care, Emergency Services",
    priceRange: "Not Available",
    contactNumber: "+91 120 2335666",
    ambulanceNumber: "108",
    address: "Sector 30, Noida, Uttar Pradesh",
    coordinates: { lat: 28.535000, lng: 77.400000 },
    gmaplink: "https://www.google.com/maps?q=Sector+30,+Noida,+Uttar+Pradesh"
  },
  {
    id: "71",
    name: "ESI Hospital",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Occupational Health, Emergency Services",
    priceRange: "Not Available",
    contactNumber: "+91 120 2445454",
    ambulanceNumber: "108",
    address: "Sector 24, Near Provident Fund Office, Noida, Uttar Pradesh",
    coordinates: { lat: 28.536000, lng: 77.401000 },
    gmaplink: "https://www.google.com/maps?q=Sector+24,+Noida,+Uttar+Pradesh"
  },
  {
    id: "72",
    name: "Ch. Brahm Prakash Ayurved Charak Sansthan",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Ayurvedic Treatments, General Medicine",
    priceRange: "Not Available",
    contactNumber: "+91 120 2454421",
    ambulanceNumber: "108",
    address: "Sector 24, Noida, Uttar Pradesh",
    coordinates: { lat: 28.537000, lng: 77.402000 },
    gmaplink: "https://www.google.com/maps?q=Sector+24,+Noida,+Uttar+Pradesh"
  },
  {
    id: "73",
    name: "Child PGI",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Pediatrics, Neonatology, Pediatric Surgery",
    priceRange: "Not Available",
    contactNumber: "+91 120 2456474",
    ambulanceNumber: "108",
    address: "Sector 30, Noida, Uttar Pradesh",
    coordinates: { lat: 28.538000, lng: 77.403000 },
    gmaplink: "https://www.google.com/maps?q=Sector+30,+Noida,+Uttar+Pradesh"
  },
  {
    id: "74",
    name: "Indira Gandhi Eye Hospital",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Ophthalmology, Eye Surgery, Vision Care",
    priceRange: "Not Available",
    contactNumber: "+91 120 2365897",
    ambulanceNumber: "108",
    address: "Sector 24, Noida, Uttar Pradesh",
    coordinates: { lat: 28.539000, lng: 77.404000 },
    gmaplink: "https://www.google.com/maps?q=Sector+24,+Noida,+Uttar+Pradesh"
  },
  {
    id: "75",
    name: "Prakash Hospital",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Multi-Specialty Care, Orthopedics, Cardiology",
    priceRange: "Not Available",
    contactNumber: "+91 120 2352354",
    ambulanceNumber: "108",
    address: "Sector 33, Noida, Uttar Pradesh",
    coordinates: { lat: 28.540000, lng: 77.405000 },
    gmaplink: "https://www.google.com/maps?q=Sector+33,+Noida,+Uttar+Pradesh"
  },
  {
    id: "76",
    name: "Community Health Center",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine, Public Health, Maternity Care",
    priceRange: "Not Available",
    contactNumber: "+91 120 2325845",
    ambulanceNumber: "108",
    address: "Sector 22, Noida, Uttar Pradesh",
    coordinates: { lat: 28.541000, lng: 77.406000 },
    gmaplink: "https://www.google.com/maps?q=Sector+22,+Noida,+Uttar+Pradesh"
  },
  {
    id: "77",
    name: "LBS Government Hospital",
    location: "Noida" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine, Emergency Services, Pediatrics",
    priceRange: "Not Available",
    contactNumber: "+91 120 2346456",
    ambulanceNumber: "108",
    address: "Sector 14, Noida, Uttar Pradesh",
    coordinates: { lat: 28.542000, lng: 77.407000 },
    gmaplink: "https://www.google.com/maps?q=Sector+14,+Noida,+Uttar+Pradesh"
  },
  {
    id: "78",
    name: "Kailash Hospital & Heart Institute",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Comprehensive Multi-specialty",
    priceRange: "Not Available",
    contactNumber: "0120-2444444",
    ambulanceNumber: "108",
    address: "H-33, H Block, Sector 27, Noida",
    coordinates: { lat: 28.543000, lng: 77.408000 },
    gmaplink: "https://www.google.com/maps?q=H-33,+H+Block,+Sector+27,+Noida"
  },
  {
    id: "79",
    name: "Max Multi Speciality Centre",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, Neurology, Orthopedics, and more",
    priceRange: "Not Available",
    contactNumber: "0120-6629999",
    ambulanceNumber: "108",
    address: "No.A-364, Opposite SAB Mall, Sector 19, Noida",
    coordinates: { lat: 28.544000, lng: 77.409000 },
    gmaplink: "https://www.google.com/maps?q=No.A-364,+Sector+19,+Noida"
  },
  {
    id: "80",
    name: "Metro Hospital and Heart Institute",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology and other medical services",
    priceRange: "Not Available",
    contactNumber: "0120-4366666",
    ambulanceNumber: "108",
    address: "Block X-1, Vyapar Marg, Sector 12, Noida",
    coordinates: { lat: 28.545000, lng: 77.410000 },
    gmaplink: "https://www.google.com/maps?q=Block+X-1,+Vyapar+Marg,+Sector+12,+Noida"
  },
  {
    id: "81",
    name: "Prakash Hospital Private Limited",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Medicine, Pediatrics, Obstetrics, and Gynecology",
    priceRange: "Not Available",
    contactNumber: "08826000033",
    ambulanceNumber: "108",
    address: "Near Iskon Temple, Sector-33, Noida",
    coordinates: { lat: 28.546000, lng: 77.411000 },
    gmaplink: "https://www.google.com/maps?q=Near+Iskon+Temple,+Sector-33,+Noida"
  },
  {
    id: "82",
    name: "Yatharth Super Speciality Hospital",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Advanced Multi-specialty Care",
    priceRange: "Not Available",
    contactNumber: "0120-2973332",
    ambulanceNumber: "108",
    address: "Plot No. 1, Sector 110, Noida",
    coordinates: { lat: 28.547000, lng: 77.412000 },
    gmaplink: "https://www.google.com/maps?q=Plot+No.+1,+Sector+110,+Noida"
  },
  {
    id: "83",
    name: "Sharda Hospital",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty",
    priceRange: "Not Available",
    contactNumber: "0120-4570000",
    ambulanceNumber: "108",
    address: "Plot No. 32-34, Knowledge Park III, Greater Noida",
    coordinates: { lat: 28.548000, lng: 77.413000 },
    gmaplink: "https://www.google.com/maps?q=Plot+No.+32-34,+Knowledge+Park+III,+Greater+Noida"
  },
  {
    id: "84",
    name: "Shree Shakti Hospital",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty",
    priceRange: "Not Available",
    contactNumber: "9654121911",
    ambulanceNumber: "108",
    address: "A-93, Sector-34, Noida",
    coordinates: { lat: 28.549000, lng: 77.414000 },
    gmaplink: "https://www.google.com/maps?q=A-93,+Sector-34,+Noida"
  },
  {
    id: "85",
    name: "Sumitra Hospital",
    location: "Noida" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Comprehensive Medical Services",
    priceRange: "Not Available",
    contactNumber: "0120-2507725",
    ambulanceNumber: "108",
    address: "A-119A, Near City Center, Sector-35, Noida",
    coordinates: { lat: 28.550000, lng: 77.415000 },
    gmaplink: "https://www.google.com/maps?q=A-119A,+Near+City+Center,+Sector-35,+Noida"
  },
  // ----------------- Ghaziabad Hospitals (Original File) -----------------
  {
    id: "22",
    name: "Manipal Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Accident and Emergency Care, Cancer Care, Cardiology, Gastrointestinal Science",
    priceRange: "₹12,000 - ₹30,000 per day",
    contactNumber: "0120-353 5353",
    ambulanceNumber: "108",
    address: "NH-24, Hapur Road, Near Landcraft Golflinks, Pandav Nagar, Ghaziabad, Uttar Pradesh, 201002",
    coordinates: { lat: 28.675000, lng: 77.440000 },
    minBeds: 14,
    maxBeds: 38,
    gmaplink: "https://www.google.com/maps?q=NH-24,+Hapur+Road,+Near+Landcraft+Golflinks,+Pandav+Nagar,+Ghaziabad,+Uttar+Pradesh+201002"
  },
  {
    id: "23",
    name: "Yashoda Super Speciality Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty",
    priceRange: "₹10,000 - ₹25,000 per day",
    contactNumber: "0120-4189500",
    ambulanceNumber: "108",
    address: "H-1, Kaushambi, Near Anand Vihar ISBT, Ghaziabad, Uttar Pradesh, 201010",
    coordinates: { lat: 28.645000, lng: 77.320000 },
    minBeds: 10,
    maxBeds: 30,
    gmaplink: "https://www.google.com/maps?q=H-1,+Kaushambi,+Ghaziabad,+Uttar+Pradesh+201010"
  },
  // ----------------- Ghaziabad - Government (Original File) -----------------
  {
    id: "24",
    name: "MMG District Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine, General Surgery, Obstetrics and Gynecology, Pediatrics",
    priceRange: "₹500 - ₹2,500 per day",
    contactNumber: "0120-2730038",
    ambulanceNumber: "108",
    address: "Near Ghanta Ghar, G.T. Road, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.668000, lng: 77.455000 },
    minBeds: 20,
    maxBeds: 45,
    gmaplink: "https://www.google.com/maps?q=Near+Ghanta+Ghar,+G.T.+Road,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "25",
    name: "New District Women Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Obstetrics and Gynecology",
    priceRange: "₹400 - ₹2,000 per day",
    contactNumber: "0120-2790400",
    ambulanceNumber: "108",
    address: "535, Gaushala Road, Kailash Nagar, Madhopura, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.671000, lng: 77.444000 },
    minBeds: 15,
    maxBeds: 35,
    gmaplink: "https://www.google.com/maps?q=535,+Gaushala+Road,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  // ----------------- Ghaziabad Hospitals from Word Document (Private) -----------------
  {
    id: "86",
    name: "Yashoda Super Speciality Hospital & Heart Institute",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-4182000",
    ambulanceNumber: "108",
    address: "III-M, Nehru Nagar, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.670000, lng: 77.430000 },
    gmaplink: "https://www.google.com/maps?q=III-M,+Nehru+Nagar,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "87",
    name: "Shreya Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-4775450",
    ambulanceNumber: "108",
    address: "Plot No. 837, Shalimar Garden Main Rd, Block C, Shalimar Garden Extension I, Ghaziabad, Uttar Pradesh, 201005",
    coordinates: { lat: 28.671000, lng: 77.431000 },
    gmaplink: "https://www.google.com/maps?q=Plot+No.+837,+Shalimar+Garden+Main+Rd,+Ghaziabad,+Uttar+Pradesh+201005"
  },
  {
    id: "88",
    name: "Astha Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Medicine, Gynecology, Obstetrics, Anesthesiology, General Surgery, Cardiology, ENT, Dentistry, Dermatology, Physiotherapy, Neurology, Urology",
    priceRange: "Not Available",
    contactNumber: "0120-2840893",
    ambulanceNumber: "108",
    address: "R-11, Sec-12, Vakeel Colony, Ghaziabad, Uttar Pradesh, 201009",
    coordinates: { lat: 28.672000, lng: 77.432000 },
    gmaplink: "https://www.google.com/maps?q=R-11,+Sec-12,+Vakeel+Colony,+Ghaziabad,+Uttar+Pradesh+201009"
  },
  {
    id: "89",
    name: "Ganesh Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-4183900",
    ambulanceNumber: "108",
    address: "2 C/3, B Block, New Kalka Garhi, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.673000, lng: 77.433000 },
    gmaplink: "https://www.google.com/maps?q=2+C/3,+B+Block,+New+Kalka+Garhi,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "90",
    name: "Navin Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "ENT, Gastroenterology, General Surgery, Cardiology, General Medicine, Dentistry",
    priceRange: "Not Available",
    contactNumber: "0886-0857401",
    ambulanceNumber: "108",
    address: "A 13/1, Opposite Cloud 9 Resorts, Meerut Road, Industrial Area, Ghaziabad, Uttar Pradesh, 201003",
    coordinates: { lat: 28.674000, lng: 77.434000 },
    gmaplink: "https://www.google.com/maps?q=A+13/1,+Opposite+Cloud+9+Resorts,+Meerut+Road,+Ghaziabad,+Uttar+Pradesh+201003"
  },
  {
    id: "91",
    name: "Heeralal Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Medicine",
    priceRange: "Not Available",
    contactNumber: "0120-2701694",
    ambulanceNumber: "108",
    address: "B28, Hapur Road, B Block, Shastri Nagar, Ghaziabad, Uttar Pradesh, 201002",
    coordinates: { lat: 28.675000, lng: 77.435000 },
    gmaplink: "https://www.google.com/maps?q=B28,+Hapur+Road,+Ghaziabad,+Uttar+Pradesh+201002"
  },
  {
    id: "92",
    name: "LYF Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "General Surgery, Gastroenterology, ENT, Nephrology, Urology, General Medicine, Anesthesiology, Gynecology and Obstetrics",
    priceRange: "Not Available",
    contactNumber: "0991-0227227",
    ambulanceNumber: "108",
    address: "NH 4 Opp. St Thomas School Gate, Street Number 4, Gyan Khand 1, Indirapuram, Ghaziabad, Uttar Pradesh, 201014",
    coordinates: { lat: 28.676000, lng: 77.436000 },
    gmaplink: "https://www.google.com/maps?q=NH+4+Opp.+St+Thomas+School+Gate,+Indirapuram,+Ghaziabad,+Uttar+Pradesh+201014"
  },
  {
    id: "93",
    name: "Pushpanjali Crosslay Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-4173000",
    ambulanceNumber: "108",
    address: "W-3, Dabur Chowk, Near Aez Mall, Vaishali Sector 1, Ghaziabad, Uttar Pradesh, 201012",
    coordinates: { lat: 28.677000, lng: 77.437000 },
    gmaplink: "https://www.google.com/maps?q=W-3,+Dabur+Chowk,+Ghaziabad,+Uttar+Pradesh+201012"
  },
  {
    id: "94",
    name: "Columbia Asia Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-3989896",
    ambulanceNumber: "108",
    address: "NH-24, Opposite Bahmeta Village, Near Golf Link, Hapur Road, Ghaziabad, Uttar Pradesh, 201005",
    coordinates: { lat: 28.678000, lng: 77.438000 },
    gmaplink: "https://www.google.com/maps?q=NH-24,+Opposite+Bahmeta+Village,+Ghaziabad,+Uttar+Pradesh+201005"
  },
  {
    id: "95",
    name: "Sarvodaya Hospital & Research Center",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-2701694",
    ambulanceNumber: "108",
    address: "K J-7, Kavi Nagar, Ghaziabad, Uttar Pradesh, 201002",
    coordinates: { lat: 28.679000, lng: 77.439000 },
    gmaplink: "https://www.google.com/maps?q=KJ-7,+Kavi+Nagar,+Ghaziabad,+Uttar+Pradesh+201002"
  },
  {
    id: "96",
    name: "Vasundhara Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-2884027",
    ambulanceNumber: "108",
    address: "15/NH-1, Near Atal Chowk, Vasundhara, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.680000, lng: 77.440000 },
    gmaplink: "https://www.google.com/maps?q=15/NH-1,+Vasundhara,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "97",
    name: "Ambay Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "9310-408197",
    ambulanceNumber: "108",
    address: "1, Lajpat Nagar, Sahibabad, Ghaziabad, Uttar Pradesh, 201005",
    coordinates: { lat: 28.681000, lng: 77.441000 },
    gmaplink: "https://www.google.com/maps?q=1,+Lajpat+Nagar,+Sahibabad,+Ghaziabad,+Uttar+Pradesh+201005"
  },
  {
    id: "98",
    name: "Kamal Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-4758888",
    ambulanceNumber: "108",
    address: "KA-Block, Opposite Kaushambi Metro Station, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.682000, lng: 77.442000 },
    gmaplink: "https://www.google.com/maps?q=KA-Block,+Opposite+Kaushambi+Metro+Station,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "99",
    name: "Meenakshi Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-2770202",
    ambulanceNumber: "108",
    address: "B-12/13, Near Dabur, Kaushambi, Ghaziabad, Uttar Pradesh, 201010",
    coordinates: { lat: 28.683000, lng: 77.443000 },
    gmaplink: "https://www.google.com/maps?q=B-12/13,+Near+Dabur,+Kaushambi,+Ghaziabad,+Uttar+Pradesh+201010"
  },
  {
    id: "100",
    name: "Santosh Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0120-2750001",
    ambulanceNumber: "108",
    address: "No 1, Opposite Old Bus Stand, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.684000, lng: 77.444000 },
    gmaplink: "https://www.google.com/maps?q=No+1,+Opposite+Old+Bus+Stand,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  // ----------------- Ghaziabad - Government from Word Document -----------------
  {
    id: "101",
    name: "District Combined Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "Information not available",
    ambulanceNumber: "108",
    address: "Sanjay Nagar, Sector 23, Rajnagar, Ghaziabad, Uttar Pradesh, 201020",
    coordinates: { lat: 28.685000, lng: 77.445000 },
    gmaplink: "https://www.google.com/maps?q=Sanjay+Nagar,+Sector+23,+Rajnagar,+Ghaziabad,+Uttar+Pradesh+201020"
  },
  {
    id: "102",
    name: "District Ayurvedic and Unani Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Ayurvedic and Unani Medicine",
    priceRange: "Not Available",
    contactNumber: "9129936504",
    ambulanceNumber: "108",
    address: "B-30 HIG Duplex, Sector-23, Sanjay Nagar, Ghaziabad, Uttar Pradesh, 201002",
    coordinates: { lat: 28.686000, lng: 77.446000 },
    gmaplink: "https://www.google.com/maps?q=B-30+HIG+Duplex,+Sector-23,+Sanjay+Nagar,+Ghaziabad,+Uttar+Pradesh+201002"
  },
  {
    id: "103",
    name: "District Homeopathic Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Homeopathic Medicine",
    priceRange: "Not Available",
    contactNumber: "9958577670",
    ambulanceNumber: "108",
    address: "District MMG Hospital Complex, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.687000, lng: 77.447000 },
    gmaplink: "https://www.google.com/maps?q=District+MMG+Hospital+Complex,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "104",
    name: "District Tuberculosis Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Tuberculosis Treatment",
    priceRange: "Not Available",
    contactNumber: "8802159400",
    ambulanceNumber: "108",
    address: "District MMG Hospital Complex, Ghaziabad, Uttar Pradesh, 201001",
    coordinates: { lat: 28.688000, lng: 77.448000 },
    gmaplink: "https://www.google.com/maps?q=District+MMG+Hospital+Complex,+Ghaziabad,+Uttar+Pradesh+201001"
  },
  {
    id: "105",
    name: "District Leprosy Hospital",
    location: "Ghaziabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Leprosy Treatment",
    priceRange: "Not Available",
    contactNumber: "9837026647",
    ambulanceNumber: "108",
    address: "CMO Office Complex, Sanjay Nagar, Ghaziabad, Uttar Pradesh, 201002",
    coordinates: { lat: 28.689000, lng: 77.449000 },
    gmaplink: "https://www.google.com/maps?q=CMO+Office+Complex,+Sanjay+Nagar,+Ghaziabad,+Uttar+Pradesh+201002"
  },
  // ----------------- Faridabad Hospitals (Original File) -----------------
  {
    id: "26",
    name: "Amrita Hospital",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Super-specialty services including oncology, cardiac sciences, neurosciences",
    priceRange: "₹15,000 - ₹38,000 per day",
    contactNumber: "0129 285 1234",
    ambulanceNumber: "108",
    address: "Mata Amritanandamayi Marg, RPS City, Sector 88, Faridabad, Haryana 121002",
    coordinates: { lat: 28.389000, lng: 77.312000 },
    minBeds: 25,
    maxBeds: 60,
    gmaplink: "https://www.google.com/maps?q=Mata+Amritanandamayi+Marg,+RPS+City,+Sector+88,+Faridabad,+Haryana+121002"
  },
  {
    id: "27",
    name: "Fortis Escorts Hospital",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, cardiac surgery, orthopedics, joint replacement, oncology, cancer care",
    priceRange: "₹14,000 - ₹33,000 per day",
    contactNumber: "0129 246 6000",
    ambulanceNumber: "108",
    address: "Neelam Bata Road, Opp. Neelam Cinema, Faridabad, Haryana 121001",
    coordinates: { lat: 28.377000, lng: 77.320000 },
    minBeds: 18,
    maxBeds: 45,
    gmaplink: "https://www.google.com/maps?q=Neelam+Bata+Road,+Faridabad,+Haryana+121001"
  },
  {
    id: "28",
    name: "B.K. Civil Hospital",
    location: "Faridabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹500 - ₹2,500 per day",
    contactNumber: "0129-2416169",
    ambulanceNumber: "108",
    address: "B.K. Chowk, Faridabad, Haryana, 121002",
    coordinates: { lat: 28.382000, lng: 77.311000 },
    minBeds: 15,
    maxBeds: 40,
    gmaplink: "https://www.google.com/maps?q=B.K.+Chowk,+Faridabad,+Haryana+121002"
  },
  {
    id: "29",
    name: "Civil Hospital",
    location: "Faridabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "General Medicine",
    priceRange: "₹500 - ₹2,000 per day",
    contactNumber: "0129-2210379",
    ambulanceNumber: "108",
    address: "Hospital Road, Near City Park, Ballabgarh",
    coordinates: { lat: 28.339000, lng: 77.324000 },
    minBeds: 12,
    maxBeds: 35,
    gmaplink: "https://www.google.com/maps?q=Hospital+Road,+Near+City+Park,+Ballabgarh"
  },
  // ----------------- Faridabad Hospitals from Word Document (Government) -----------------
  {
    id: "106",
    name: "Arsh Multispecialty Hospital",
    location: "Faridabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "9640433300",
    ambulanceNumber: "108",
    address: "Tigaon Road, Sector 78, Greater Faridabad",
    coordinates: { lat: 28.380000, lng: 77.310000 },
    gmaplink: "https://www.google.com/maps?q=Tigaon+Road,+Sector+78,+Faridabad"
  },
  {
    id: "107",
    name: "R.K. Hospital",
    location: "Faridabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "0129-2413430",
    ambulanceNumber: "108",
    address: "NIT-3, Faridabad",
    coordinates: { lat: 28.380000, lng: 77.310000 },
    gmaplink: "https://www.google.com/maps?q=NIT-3,+Faridabad"
  },
  {
    id: "108",
    name: "Manavta Hospital",
    location: "Faridabad" as LocationType,
    type: "Government" as HospitalType,
    specialization: "Not Specified",
    priceRange: "Not Available",
    contactNumber: "9999001711",
    ambulanceNumber: "108",
    address: "Uncha Gaon, Ballabhgarh",
    coordinates: { lat: 28.380000, lng: 77.310000 },
    gmaplink: "https://www.google.com/maps?q=Uncha+Gaon,+Ballabhgarh"
  },
  // ----------------- Faridabad Hospitals from Word Document (Private) -----------------
  {
    id: "109",
    name: "Asian Institute of Medical Sciences",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty including cardiology, oncology, nephrology, gastroenterology",
    priceRange: "Not Available",
    contactNumber: "0129 425 3000",
    ambulanceNumber: "108",
    address: "Badkal Flyover Road, Sector 21A, Faridabad, Haryana 121001",
    coordinates: { lat: 28.379000, lng: 77.311000 },
    gmaplink: "https://www.google.com/maps?q=Badkal+Flyover+Road,+Sector+21A,+Faridabad,+Haryana+121001"
  },
  {
    id: "110",
    name: "Metro Hospital and Heart Institute",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Cardiology, cardiac surgery, multi-specialty services",
    priceRange: "Not Available",
    contactNumber: "0129 427 7777",
    ambulanceNumber: "108",
    address: "Sector 16A, Faridabad, Haryana 121002",
    coordinates: { lat: 28.378000, lng: 77.312000 },
    gmaplink: "https://www.google.com/maps?q=Sector+16A,+Faridabad,+Haryana+121002"
  },
  {
    id: "111",
    name: "Sarvodaya Hospital and Research Centre",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Robotic surgery, minimally invasive treatments, fertility care, gynecology, kidney transplants, nephrology",
    priceRange: "Not Available",
    contactNumber: "078381 14428",
    ambulanceNumber: "108",
    address: "YMCA Road, Sector-8, Near ESI Hospital, Faridabad, Haryana 121006",
    coordinates: { lat: 28.377500, lng: 77.312500 },
    gmaplink: "https://www.google.com/maps?q=YMCA+Road,+Sector-8,+Faridabad,+Haryana+121006"
  },
  {
    id: "112",
    name: "QRG Central Hospital & Research Centre",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty services",
    priceRange: "Not Available",
    contactNumber: "0129 409 0300",
    ambulanceNumber: "108",
    address: "69, Delhi Mathura Road, Near Neelam Flyover, Ajronda Chowk, Sector 20A, Faridabad, Haryana 121001",
    coordinates: { lat: 28.377000, lng: 77.313000 },
    gmaplink: "https://www.google.com/maps?q=69,+Delhi+Mathura+Road,+Faridabad,+Haryana+121001"
  },
  {
    id: "113",
    name: "Park Hospital",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty services",
    priceRange: "Not Available",
    contactNumber: "0129 420 0000",
    ambulanceNumber: "108",
    address: "Opposite Court, J Block, Sector 10 HBC, Faridabad, Haryana 121006",
    coordinates: { lat: 28.376500, lng: 77.313500 },
    gmaplink: "https://www.google.com/maps?q=Opposite+Court,+J+Block,+Sector+10+HBC,+Faridabad,+Haryana+121006"
  },
  {
    id: "114",
    name: "IBS Hospital",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty services",
    priceRange: "Not Available",
    contactNumber: "0129 222 2222",
    ambulanceNumber: "108",
    address: "8 - D 1, YMCA Road, Sector 11, Faridabad, Haryana 121006",
    coordinates: { lat: 28.376000, lng: 77.314000 },
    gmaplink: "https://www.google.com/maps?q=8-D+1,+YMCA+Road,+Sector+11,+Faridabad,+Haryana+121006"
  },
  {
    id: "115",
    name: "Shivalik Hospital",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty services",
    priceRange: "Not Available",
    contactNumber: "0129 410 7777",
    ambulanceNumber: "108",
    address: "Huda Market, Sector 37, Faridabad, Haryana 121003",
    coordinates: { lat: 28.375500, lng: 77.314500 },
    gmaplink: "https://www.google.com/maps?q=Huda+Market,+Sector+37,+Faridabad,+Haryana+121003"
  },
  {
    id: "116",
    name: "Ghai Hospital",
    location: "Faridabad" as LocationType,
    type: "Private" as HospitalType,
    specialization: "Multi-specialty services",
    priceRange: "Not Available",
    contactNumber: "0129 228 3000",
    ambulanceNumber: "108",
    address: "Plot No-29, Sector 9, Faridabad, Haryana 121006",
    coordinates: { lat: 28.375000, lng: 77.315000 },
    gmaplink: "https://www.google.com/maps?q=Plot+No-29,+Sector+9,+Faridabad,+Haryana+121006"
  }
];

// Create the final hospital list with dynamic bed availability.
export const hospitals: Hospital[] = hospitalData.map(hospital => ({
  ...hospital,
  bedsAvailable: getRandomBedsAvailable(hospital.minBeds || 1, hospital.maxBeds || 10)
}));

// Update bed availability periodically (every 3 minutes)
setInterval(() => {
  hospitalData.forEach((hospital, index) => {
    hospitals[index].bedsAvailable = getRandomBedsAvailable(hospital.minBeds || 1, hospital.maxBeds || 10);
  });
}, 1000 * 60 * 3);